# Generated by Django 5.1.4 on 2024-12-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePessoa', models.CharField(max_length=100)),
                ('sobrenomePessoa', models.CharField(max_length=100)),
                ('telefonePessoa', models.CharField(max_length=20)),
            ],
        ),
    ]
