# Generated by Django 5.1.4 on 2024-12-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='nomePessoa',
            new_name='nome_pessoa',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='sobrenomePessoa',
            new_name='sobrenome_pessoa',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='telefonePessoa',
            new_name='telefone_pessoa',
        ),
    ]
