# Generated by Django 5.1.4 on 2024-12-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_app', '0002_rename_nomepessoa_registro_nome_pessoa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='registroPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePessoa', models.CharField(max_length=100)),
                ('sobrenomePessoa', models.CharField(max_length=100)),
                ('telefonePessoa', models.CharField(max_length=20)),
                ('estadoPessoa', models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
