# Generated by Django 5.1.4 on 2024-12-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_app', '0003_registropessoa_delete_registro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registroPessoa',
            new_name='registrarPessoa',
        ),
    ]
