# Generated by Django 5.1.4 on 2024-12-14 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_app', '0004_rename_registropessoa_registrarpessoa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registrarPessoa',
            new_name='Pessoa',
        ),
    ]
